version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: phoenix_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phoenix_network

networks:
  phoenix_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
